import { readFile, writeFile, mkdir, cp, access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
process.chdir(root);
const projects = JSON.parse(await readFile('content/projects.json', 'utf8'));
const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const slugs = new Set(projects.map(p => p.slug));
if (slugs.size !== projects.length) throw new Error('Duplicate project slug');
for (const p of projects) {
  for (const key of ['slug', 'name', 'category', 'eyebrow', 'summary', 'problem', 'solution', 'engineering', 'reviewed']) {
    if (typeof p[key] !== 'string' || !p[key].trim()) throw new Error(`${p.slug}: missing ${key}`);
  }
  if (!/^[a-z0-9-]+$/.test(p.slug) || !/^#[0-9a-f]{6}$/i.test(p.accent)) throw new Error(`Invalid slug or accent: ${p.slug}`);
  if (!['Commerce', 'Platforms', 'Mobile', 'Hardware'].includes(p.category)) throw new Error(`Invalid category: ${p.slug}`);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(p.reviewed)) throw new Error(`Invalid review date: ${p.slug}`);
  for (const key of ['features', 'stack', 'flow', 'related', 'links']) if (!Array.isArray(p[key])) throw new Error(`Missing ${key}: ${p.slug}`);
  for (const related of p.related) if (!slugs.has(related)) throw new Error(`Unknown related project: ${related}`);
  for (const link of p.links) if (new URL(link.url).protocol !== 'https:') throw new Error(`Non-HTTPS link: ${p.slug}`);
  await access(`assets/images/${p.image}`);
}

await mkdir('dist', { recursive: true });
for (const name of ['assets', 'index.html', '_worker.js']) await cp(name, `dist/${name}`, { recursive: true });
const base = 'https://portfolio.innovorix.com';
const tags = p => p.stack.map(t => `<span>${escape(t)}</span>`).join('');
const link = l => `<a class="button" href="${escape(l.url)}" target="_blank" rel="noopener noreferrer">${escape(l.label)} <span aria-hidden="true">↗</span></a>`;
const card = p => `<a class="project-card" href="./about-${p.slug}" data-category="${escape(p.category)}" data-search="${escape(`${p.name} ${p.summary} ${p.stack.join(' ')}`.toLowerCase())}" style="--accent:${p.accent}"><div class="card-image"><img src="./assets/images/${p.image}" alt="${escape(p.name)} project artwork" loading="lazy" width="800" height="600"><span class="card-category">${escape(p.category)}</span></div><div class="card-copy"><div class="card-heading"><h3>${escape(p.name)}</h3><span aria-hidden="true">↗</span></div><p>${escape(p.summary)}</p><div class="tags">${p.stack.slice(0,3).map(t=>`<span>${escape(t)}</span>`).join('')}</div></div></a>`;
const layout = (title, description, path, body, extra = '') => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="dark"><title>${escape(title)} | M Hamid Jamil</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${base}/${path}"><meta property="og:type" content="website"><meta property="og:title" content="${escape(title)} | M Hamid Jamil"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${base}/${path}"><meta property="og:image" content="${base}/assets/images/showcase-cover.svg"><link rel="icon" href="./assets/images/logo.ico"><link rel="stylesheet" href="./assets/css/showcase.css">${extra}</head>
<body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="wordmark" href="./work" aria-label="M Hamid Jamil, selected work">HJ<span class="brand-dot">.</span><span class="wordmark-label">M HAMID JAMIL</span></a><nav aria-label="Main navigation"><a href="./work">Work</a><a href="./index.html">About me</a><a href="https://github.com/mhamidjamil">GitHub <span aria-hidden="true">↗</span></a></nav></header>${body}<footer><a class="wordmark" href="./work">HJ<span class="brand-dot">.</span></a><p>Built with care, from Lahore, Pakistan.</p><a href="https://www.linkedin.com/in/muhammad-hamid-jamil-009b5916b/">Let's connect ↗</a></footer></body></html>`;

const gallery = `<main id="main"><section class="gallery-hero"><div><p class="eyebrow"><span class="signal"></span> SOFTWARE · MOBILE · CONNECTED HARDWARE</p><h1>Ideas become<br>systems people <em>use.</em></h1><p class="intro">I'm Hamid. I build the whole journey: the interface people touch, the services behind it, and the devices that connect it to the world.</p><div class="hero-actions"><a class="button primary" href="#projects">Explore the work <span aria-hidden="true">↓</span></a><a class="text-link" href="https://github.com/mhamidjamil">Find me on GitHub ↗</a></div></div><aside class="system-art" aria-label="Engineering across interfaces, services and hardware"><span class="art-caption">FROM THE SCREEN TO THE CIRCUIT</span><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="art-core">HJ<span>.</span></div><span class="art-node node-one">WEB</span><span class="art-node node-two">MOBILE</span><span class="art-node node-three">CLOUD</span><span class="art-node node-four">HARDWARE</span><span class="art-bottom">Interfaces. Services. Real-world signals.</span></aside></section><div class="discipline-bar"><span>Commerce & operations</span><span>Mobile experiences</span><span>Shared infrastructure</span><span>Embedded systems</span></div><section id="projects" class="work-section"><div class="section-top"><div><p class="eyebrow">THE WORK, IN DETAIL</p><h2>Selected projects<span class="muted"> / ${projects.length}</span></h2></div><label class="search-label">Find a project<input id="search" type="search" placeholder="Name, technology or idea…" autocomplete="off"></label></div><div class="filters" role="group" aria-label="Filter projects">${['All', 'Commerce', 'Platforms', 'Mobile', 'Hardware'].map((c,i)=>`<button type="button" data-filter="${c}" aria-pressed="${i===0}">${c}</button>`).join('')}</div><p class="results" id="results" role="status">${projects.length} projects</p><div class="project-grid">${projects.map(card).join('')}</div><p id="empty" hidden>No projects match. Try another name or choose All.</p></section><section class="closing"><p class="eyebrow">A COMMON THREAD</p><h2>Good software connects<br>the things that matter.</h2><p>A customer to a kitchen. An institute to a family. A phone to a physical device. That is the work I enjoy building.</p><a class="button primary" href="https://www.linkedin.com/in/muhammad-hamid-jamil-009b5916b/">Talk about your project ↗</a></section></main><script src="./assets/js/showcase.js" defer></script>`;
await writeFile('dist/work.html', layout('Selected work', 'Web platforms, mobile applications and connected hardware built by M Hamid Jamil. Explore the projects and the engineering behind them.', 'work', gallery));

for (const p of projects) {
  const related = p.related.map(s => projects.find(x => x.slug === s));
  const body = `<main id="main" style="--accent:${p.accent}"><section class="case-hero"><a class="back-link" href="./work">← All work</a><div class="case-title-row"><div><p class="eyebrow">${escape(p.category)} / ${escape(p.eyebrow)}</p><h1>${escape(p.name)}</h1><p class="case-summary">${escape(p.summary)}</p></div><div class="case-links">${p.links.map(link).join('')}</div></div><div class="case-meta"><span>Built by M Hamid Jamil</span><span>Content reviewed <time datetime="${p.reviewed}">${p.reviewed}</time></span></div><div class="case-cover"><img src="./assets/images/${p.image}" alt="${escape(p.name)} project artwork" width="1200" height="800" fetchpriority="high"><div class="cover-caption"><span>${escape(p.eyebrow)}</span><span>PROJECT / ${String(projects.indexOf(p)+1).padStart(2,'0')}</span></div></div></section><div class="case-body"><article><section><p class="eyebrow">01 / THE CONTEXT</p><h2>Why this exists</h2><p>${escape(p.problem)}</p></section><section><p class="eyebrow">02 / THE BUILD</p><h2>What I built</h2><p>${escape(p.solution)}</p><ul class="features">${p.features.map(f=>`<li>${escape(f)}</li>`).join('')}</ul></section><section><p class="eyebrow">03 / THE ENGINEERING</p><h2>How it fits together</h2><p>${escape(p.engineering)}</p><ol class="flow">${p.flow.map((f,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span>${escape(f)}</li>`).join('')}</ol></section></article><aside class="project-details"><p class="eyebrow">BUILT WITH</p><div class="tags">${tags(p)}</div><hr><p class="eyebrow">EXPLORE THE CONNECTIONS</p>${related.map(r=>`<a class="related-link" href="./about-${r.slug}"><span>${escape(r.name)}</span><span aria-hidden="true">↗</span></a>`).join('')}<hr><p>Have a similar problem to solve?</p><a class="text-link" href="https://www.linkedin.com/in/muhammad-hamid-jamil-009b5916b/">Let's talk ↗</a></aside></div><section class="more-work"><div class="section-top"><h2>Keep exploring</h2><a class="text-link" href="./work">All projects ↗</a></div><div class="project-grid">${related.slice(0,3).map(card).join('')}</div></section></main>`;
  await writeFile(`dist/about-${p.slug}.html`, layout(p.name, p.summary, `about-${p.slug}`, body));
}
await writeFile('dist/_redirects', '/about-inovorix /about-innovorix 301\n/about-academia /about-innovorix 301\n/about-textgate /about-spotwire 301\n/about-lilibet /about-lilibetlondon 301\n/about-whatsapp-gateway /about-baileys 301\n');
await writeFile('dist/robots.txt', `User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);
await writeFile('dist/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['', 'work', ...projects.map(p=>`about-${p.slug}`)].map(p=>`<url><loc>${base}/${p}</loc></url>`).join('')}</urlset>`);
await writeFile('dist/_headers', '/assets/*\n  X-Content-Type-Options: nosniff\n/*\n  Referrer-Policy: strict-origin-when-cross-origin\n');
await writeFile('dist/version.json', await readFile('version.json', 'utf8'));
console.log(`Built ${projects.length} case studies and work gallery. All project references and image files validated.`);
